---
title: "Data Visulaization with Examples"
output: pdf_document
---



```{r}
housing.df <- read.csv("C:\\Users\\arjun\\Documents\\GitHub\\datamining\\BostonHousing.csv")
head(housing.df,9)
```

```{r}
## scatter plot with axes names
plot(housing.df$medv ~ housing.df$lstat, xlab = "MDEV", ylab = "LSTAT")
```

```{r}
# alternative plot with ggplot
library(ggplot2)
ggplot(housing.df) + geom_point(aes(x = lstat, y = medv), colour = "navy", alpha = 0.7)
```

```{r}
## barchart of CHAS vs. mean MEDV
# compute mean MEDV per CHAS = (0, 1)
data.for.plot <- aggregate(housing.df$medv, by = list(housing.df$chas), FUN = mean)
names(data.for.plot) <- c("CHAS", "MeanMEDV")
barplot(data.for.plot$MeanMEDV, names.arg = data.for.plot$CHAS,
        xlab = "CHAS", ylab = "Avg. MEDV")
```

```{r}
# alternative plot with ggplot
ggplot(data.for.plot) + geom_bar(aes(x = CHAS, y = MeanMEDV), stat = "identity")

```

```{r}
## histogram of MEDV
hist(housing.df$medv, xlab = "MEDV")
```

```{r}
# alternative plot with ggplot
ggplot(housing.df) + geom_histogram(aes(x = medv), binwidth = 5 , color = "light blue", fill = "blue")


```
```{r}
## boxplot of MEDV for different values of CHAS
boxplot(housing.df$medv ~ housing.df$chas, xlab = "CHAS", ylab = "MEDV")
```

```{r}
# alternative plot with ggplot
ggplot(housing.df) + geom_boxplot(aes(x = as.factor(chas), y = medv)) + xlab("CHAS")


```

```{r}
names(housing.df) <- toupper(names(housing.df))
housing.df$CAT.MEDV <- ifelse(housing.df$MEDV > 30,1,0)
data.for.plot <- aggregate(housing.df$CAT.MEDV, by = list(housing.df$CHAS), FUN = mean)
names(data.for.plot) <- c("CHAS", "MeanCATMEDV")
barplot(data.for.plot$MeanCATMEDV * 100, names.arg = data.for.plot$CHAS,
xlab = "CHAS", ylab = "% of CAT.MEDV" , col = "light blue")

```


```{r}
cor.mat <- round(cor(housing.df),2) # rounded correlation matrix
library(reshape2)
library(ggplot2)
melted.cor.mat <- melt(cor.mat)
ggplot(melted.cor.mat, aes(x = Var1 , y = Var2, fill = value)) +
geom_tile() +
geom_text(aes(label = value))

```

```{r}
#although no missing values , the respective plots the missing values in binary converted file
heatmap(1 * is.na(housing.df), Rowv = NA, Colv = NA)

```


```{r}

## color plot
par(xpd=TRUE) # allow legend to be displayed outside of plot area
plot(housing.df$NOX ~ housing.df$LSTAT, ylab = "NOX", xlab = "LSTAT",
col = ifelse(housing.df$CAT..MEDV == 1, "black", "gray"))
# add legend outside of plotting area
# In legend() use argument inset = to control the location of the legend relative
# to the plot.
legend("topleft", inset=c(0, -0.2),
legend = c("CAT.MEDV = 1", "CAT.MEDV = 0"), col = c("black", "gray"),
pch = 1, cex = 0.5)
# alternative plot with ggplot
library(ggplot2)
ggplot(housing.df, aes(y = NOX, x = LSTAT, colour= CAT.MEDV)) +
geom_point(alpha = 0.6)
## panel plots
# compute mean MEDV per RAD and CHAS
# In aggregate() use argument drop = FALSE to include all combinations
# (exiting and missing) of RAD X CHAS.
data.for.plot <- aggregate(housing.df$MEDV, by = list(housing.df$RAD, housing.df$CHAS),
FUN = mean, drop = FALSE)
names(data.for.plot) <- c("RAD", "CHAS", "meanMEDV")
# plot the data
par(mfcol = c(2,1))
barplot(height = data.for.plot$meanMEDV[data.for.plot$CHAS == 0],
names.arg = data.for.plot$RAD[data.for.plot$CHAS == 0],
xlab = "RAD", ylab = "Avg. MEDV", main = "CHAS = 0")
barplot(height = data.for.plot$meanMEDV[data.for.plot$CHAS == 1],
names.arg = data.for.plot$RAD[data.for.plot$CHAS == 1],
xlab = "RAD", ylab = "Avg. MEDV", main = "CHAS = 1")
# alternative plot with ggplot
ggplot(data.for.plot) +
geom_bar(aes(x = as.factor(RAD), y = `meanMEDV`), stat = "identity") +
xlab("RAD") + facet_grid(CHAS ~ .)
```


```{r}
# alternative, nicer plot (displayed)
library(GGally)
ggpairs(housing.df[, c(1, 3, 12, 13)])
```

```{r}
options(scipen=999) # avoid scientific notation
## scatter plot: regular and log scale
plot(housing.df$MEDV ~ housing.df$CRIM, xlab = "CRIM", ylab = "MEDV")
# to use logarithmic scale set argument log = to either 'x', 'y', or 'xy'.
plot(housing.df$MEDV ~ housing.df$CRIM,
xlab = "CRIM", ylab = "MEDV", log = 'xy')
# alternative log-scale plot with ggplot
library(ggplot2)
ggplot(housing.df) + geom_point(aes(x = CRIM, y = MEDV)) +
scale_x_log10(breaks = 10^(-2:2),
labels = format(10^(-2:2), scientific = FALSE, drop0trailing = TRUE)) +
scale_y_log10(breaks = c(5, 10, 20, 40))
## boxplot: regular and log scale
boxplot(housing.df$CRIM ~ housing.df$CAT.MEDV,
xlab = "CAT.MEDV", ylab = "CRIM")
boxplot(housing.df$CRIM ~ housing.df$CAT.MEDV,
xlab = "CAT.MEDV", ylab = "CRIM", log = 'y')

```